/* TecnoMath · Catálogo dinámico */
(function(){'use strict';
const CATALOG='data/games.json';
const SUPABASE_URL='https://xdszveoxdrdnwwzzvkav.supabase.co';
const SUPABASE_KEY='sb_publishable_xwUE0aN1g0rb7aOLyXPAsA_kOAX9bOA';
function loadAuth(){return new Promise((resolve,reject)=>{if(window.TecnomathAuth)return resolve();const old=document.querySelector('script[data-tecnomath-auth]');if(old){old.addEventListener('load',resolve,{once:true});old.addEventListener('error',()=>reject(new Error('No se pudo cargar la autenticación TecnoMath.')),{once:true});return}const s=document.createElement('script');s.src='js/tecnomath-auth.js?v=20260914';s.dataset.tecnomathAuth='true';s.onload=resolve;s.onerror=()=>reject(new Error('No se pudo cargar la autenticación TecnoMath.'));document.head.appendChild(s)});}
function loadAdminPortal(){return new Promise((resolve)=>{if(document.querySelector('script[data-tecnomath-admin-portal]'))return resolve();const s=document.createElement('script');s.src='js/tecnomath-admin-portal.js?v=20260914';s.dataset.tecnomathAdminPortal='true';s.onload=resolve;s.onerror=()=>resolve();document.head.appendChild(s)})}
function addMeta(property,content){let m=document.head.querySelector(`meta[property="${property}"]`);if(!m){m=document.createElement('meta');m.setAttribute('property',property);document.head.appendChild(m)}m.content=content}
addMeta('og:title','TecnoMath | Plataforma Educativa Interactiva');addMeta('og:description','Juegos educativos, retos matemáticos y experiencias interactivas en TecnoMath.');addMeta('og:image','https://tecnomath.online/img/mindmath.png');addMeta('og:type','website');
const nativeFetch=window.fetch.bind(window);
window.fetch=function(input,init){try{const u=typeof input==='string'?input:input&&input.url||'';if(/(?:^|\/)juegos\.json(?:\?|$)/i.test(u)){const replacement=new URL(CATALOG,location.href).href;return nativeFetch(replacement,init)}}catch(e){}return nativeFetch(input,init)};
function gameKey(g){const submission=String(g&&g.submissionId||'').trim();if(submission)return submission;const url=String(g&&g.url||'').trim();const name=String(g&&g.name||'').trim();if(url==='games/jinete11°/index.html')return `${url}::${name}`;return url||name}
function injectStyles(){if(document.getElementById('tm-loader-styles'))return;const s=document.createElement('style');s.id='tm-loader-styles';s.textContent=`#projectsContainer .project-card{transition:transform .25s ease,box-shadow .25s ease,border-color .25s ease}#projectsContainer .project-card:hover{transform:translateY(-6px)}#projectsContainer .project-card.tm-ordered{animation:tmCardIn .45s ease both}@keyframes tmCardIn{from{opacity:.1;transform:translateY(14px)}to{opacity:1;transform:translateY(0)}}.tm-order-badge{position:absolute;top:10px;left:10px;z-index:30;padding:5px 8px;border-radius:999px;background:#060610dd;border:1px solid #00f5ff;color:#00f5ff;font:700 10px Arial}.tm-favorite{position:absolute;top:10px;right:10px;z-index:40;border:1px solid #ffffff44;border-radius:50%;background:#060610cc;color:#fff;width:38px;height:38px;cursor:pointer;font-size:20px}.tm-favorite.active{color:#ff2bd6;box-shadow:0 0 16px #ff2bd666}.tm-search-wrap{max-width:900px;margin:15px auto;padding:0 14px}.tm-search{width:100%;padding:13px 16px;border-radius:12px;border:1px solid #00f5ff55;background:#090914;color:#fff;outline:none;font:600 14px Arial}.tm-no-results{grid-column:1/-1;text-align:center;padding:35px;color:#aaa;font:14px Arial} @media(prefers-reduced-motion:reduce){#projectsContainer .project-card{animation:none!important;transition:none!important}}`;document.head.appendChild(s)}
async function supabase(){if(window.supabase&&window.supabase.createClient)return window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);await new Promise((resolve,reject)=>{const sc=document.createElement('script');sc.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.0/dist/umd/supabase.min.js';sc.onload=resolve;sc.onerror=reject;document.head.appendChild(sc)});return window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY)}
async function getOrder(){try{const db=await supabase();const {data,error}=await db.from('tecnomath_game_catalog_order').select('game_key,sort_order').order('sort_order',{ascending:true}).order('game_key',{ascending:true});if(error)throw error;return data||[]}catch(e){console.warn('Orden Supabase no disponible:',e.message);return[]}}
async function loadCatalog(){try{const r=await nativeFetch(`${CATALOG}?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);const data=await r.json();if(!Array.isArray(data))throw Error('games.json debe ser una lista');window.TecNoMathCatalog=data;injectStyles();console.log(`📚 Catálogo oficial: ${data.length} juegos`)}catch(e){console.warn('No se pudo cargar el catálogo oficial:',e.message)}}
function isEventGame(g){return g&&g.evento!==null&&g.evento!==undefined&&String(g.evento).trim()!==''}
async function applyOrder(){if(document.readyState==='loading')return;const box=document.getElementById('projectsContainer');if(!box)return;const rows=[...box.querySelectorAll('.project-card')];if(!rows.length)return;const orders=await getOrder();if(!orders.length)return;const data=Array.isArray(window.TecNoMathCatalog)?window.TecNoMathCatalog:[];const catalogByKey=new Map(data.map(g=>[gameKey(g),g]));const normalKeys=new Set(data.filter(g=>!isEventGame(g)).map(gameKey));const eventKeys=new Set(data.filter(isEventGame).map(gameKey));const normalRank=new Map();const eventRank=new Map();let normalPos=0,eventPos=0;orders.forEach(x=>{const k=String(x.game_key);if(normalKeys.has(k))normalRank.set(k,normalPos++);else if(eventKeys.has(k))eventRank.set(k,eventPos++)});const keyByName=new Map(data.map(g=>[`${String(g.name||'').trim().toLowerCase()}|${String(g.url||'').trim().toLowerCase()}`,gameKey(g)]));const getRowKey=row=>{const name=(row.querySelector('.project-name')?.textContent||'').replace(/🎃|🎄|🎂|🎡|🔥|⚽/g,'').trim().toLowerCase();const href=(row.getAttribute('href')||'').trim().toLowerCase();return keyByName.get(`${name}|${href}`)||href||name};const rankFor=row=>{const k=getRowKey(row);const g=catalogByKey.get(k);const rank=isEventGame(g)?eventRank:normalRank;return rank.has(k)?rank.get(k):Number.MAX_SAFE_INTEGER};rows.sort((a,b)=>rankFor(a)-rankFor(b));rows.forEach((row,i)=>{row.classList.add('tm-ordered');row.style.setProperty('--tm-index',i);box.appendChild(row)})}
function installSearch(){if(document.getElementById('tm-search'))return;const box=document.getElementById('projectsContainer');if(!box||!box.parentNode)return;const wrap=document.createElement('div');wrap.className='tm-search-wrap';wrap.innerHTML='<input id="tm-search" class="tm-search" type="search" placeholder="🔎 Buscar un juego por nombre, categoría o descripción…" aria-label="Buscar juego">';box.parentNode.insertBefore(wrap,box);document.getElementById('tm-search').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();box.querySelectorAll('.project-card').forEach(card=>{card.classList.toggle('tm-search-hidden',!!q&&!card.textContent.toLowerCase().includes(q))})})}
function markCards(){const box=document.getElementById('projectsContainer');if(!box)return;box.querySelectorAll('.project-card').forEach((card,i)=>{if(!card.querySelector('.tm-order-badge')){const b=document.createElement('span');b.className='tm-order-badge';b.textContent=`#${i+1}`;card.style.position='relative';card.appendChild(b)}})}
async function boot(){await loadCatalog();try{await loadAuth();await loadAdminPortal()}catch(e){console.error('TecnoMath Auth:',e)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(async()=>{installSearch();await applyOrder();markCards()},700),{once:true});else setTimeout(async()=>{installSearch();await applyOrder();markCards()},700);setTimeout(async()=>{await applyOrder();markCards()},2500)}
boot();window.TecnoMathCatalogReload=async()=>{await loadCatalog();await applyOrder();markCards()};
})();
