/* TecnoMath · Lógica del orden del catálogo */
'use strict';

(function(){
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
  const auth=window.TecnomathAuth;
  let db=null,games=[],original=[],history=[],saving=false;
  const BUILTIN_GAMES=[{name:'MENTEX',desc:'Juego educativo MENTEX',url:'games/jolberth11°/index.html',imageUrl:'',icon:'🎮',category:'edu',deviceCompatibility:'both',evento:null,sourceType:'internal'}];
  const isEvent=g=>g&&g.evento!==null&&g.evento!==undefined&&String(g.evento).trim()!=='';
  const isStudentGame=g=>String(g?.sourceType||'').toLowerCase()==='upload'||Boolean(String(g?.submissionId||'').trim());
  function key(g){const submission=String(g?.submissionId||'').trim();if(submission)return submission;const url=String(g?.url||'').trim();const name=String(g?.name||'').trim();if(url==='games/jinete11°/index.html')return `${url}::${name}`;return url||name}
  function image(g){const src=String(g?.imageUrl||'').trim();if(!src)return'';if(/^(?:https?:|data:|\/)/i.test(src))return src;return new URL(src.replace(/^\.\//,''),window.location.origin+'/').href}
  function setStatus(t,type='ok'){$('status').innerHTML=t;$('status').className='status '+type}
  function mergeUnique(base,extra){const out=[...base],seen=new Set(out.map(key));for(const g of extra){if(!g||!g.url)continue;const k=key(g);if(!seen.has(k)){seen.add(k);out.push(g)}}return out}
  function submissionToGame(s){const gameUrl=String(s?.published_url||s?.game_url||'').trim();if(!gameUrl)return null;return {name:String(s?.name||'Juego sin nombre').trim(),desc:String(s?.description||'Juego publicado por un usuario').trim(),url:gameUrl,imageUrl:String(s?.image_url||'').trim(),icon:String(s?.icon||'🎮'),category:String(s?.category||'otros'),deviceCompatibility:'both',evento:null,sourceType:'upload',submissionId:String(s?.id||''),authorName:String(s?.author_name||'Usuario').trim(),authorEmail:String(s?.author_email||'').trim(),publishedPath:String(s?.published_path||'').trim()}}
  function snapshot(){return games.map(key)}
  function markChanged(){const changed=games.map(key).join('|')!==original.map(key).join('|');$('undo').style.display=history.length?'inline-block':'none';$('save').disabled=saving||!changed;$('reload').disabled=saving;$('reset').disabled=saving;$('history').textContent=changed?`🟡 Cambios pendientes · ${history.length} movimiento${history.length===1?'':'s'}`:'✅ Orden local y orden guardado coinciden';}
  function renderPreview(){const p=$('preview');p.innerHTML=games.slice(0,20).map((g,i)=>{const src=esc(image(g)),name=esc(g.name);return `<div class="preview-item"><div class="preview-num">#${i+1}</div>${src?`<img src="${src}" alt="" loading="lazy" onerror="this.style.display='none'">`:''}<div class="preview-name">${name}</div></div>`}).join('')}
  function sectionHtml(items,q){const filtered=items.map((g,i)=>({g,i})).filter(x=>!q||`${x.g.name} ${x.g.desc||''} ${x.g.category||''} ${x.g.authorName||''}`.toLowerCase().includes(q));if(!filtered.length)return'<div class="muted">No se encontraron juegos.</div>';return `<section class="section"><div class="section-head"><div class="section-title">🎓 Juegos de estudiantes</div><div class="section-count">${filtered.length} visibles · ${items.length} totales</div></div><div class="game-list">${filtered.map(({g,i})=>rowHtml(g,i,items.length)).join('')}</div></section>`}
  function rowHtml(g,i,total){const src=esc(image(g)),icon=esc(g.icon||'🎮'),name=esc(g.name),student=isStudentGame(g);return `<article class="game-row" data-index="${i}"><div class="position-box"><label>PUESTO</label><input class="position-input" type="number" min="1" max="${total}" value="${i+1}" aria-label="Puesto de ${name}" title="Escribe el puesto y pulsa Enter"></div><div class="thumb">${src?`<img src="${src}" alt="Logo de ${name}" loading="lazy" decoding="async" onerror="this.style.display='none';this.nextElementSibling.style.display='flex'">`:''}<div class="thumb-fallback">${icon}</div></div><div><div class="name">${name}${student?'<span class="source-badge">🎓 ESTUDIANTE</span>':''}</div><div class="meta">${esc(g.category||'otros')} · ${esc(g.authorName||'TecnoMath')}</div></div><div class="move-buttons"><button type="button" data-move="up" title="Subir" ${i===0?'disabled':''}>↑</button><button type="button" data-move="down" title="Bajar" ${i===total-1?'disabled':''}>↓</button></div></article>`}
  function render(){const q=$('search').value.trim().toLowerCase();$('sections').innerHTML=sectionHtml(games,q);document.querySelectorAll('.game-row').forEach(row=>{row.querySelectorAll('[data-move]').forEach(btn=>btn.addEventListener('click',()=>move(Number(row.dataset.index),btn.dataset.move==='up'?-1:1)));row.querySelector('.position-input').addEventListener('keydown',e=>{if(e.key!=='Enter')return;e.preventDefault();const input=e.currentTarget;moveTo(Number(row.dataset.index),Number(input.value));input.blur()});row.querySelector('.position-input').addEventListener('change',e=>{const target=Number(e.currentTarget.value);if(Number.isInteger(target))moveTo(Number(row.dataset.index),target)});});markChanged();renderPreview()}
  function move(i,d){if(saving)return;const j=i+d;if(i<0||j<0||j>=games.length)return;history.push(snapshot());if(history.length>50)history.shift();[games[i],games[j]]=[games[j],games[i]];render()}
  function moveTo(from,target){if(saving||from<0||from>=games.length)return;target=Math.max(1,Math.min(games.length,Math.trunc(target||0)))-1;if(from===target)return;history.push(snapshot());if(history.length>50)history.shift();const item=games.splice(from,1)[0];games.splice(target,0,item);render()}
  function undo(){if(!history.length||saving)return;const keys=history.pop(),map=new Map(games.map(g=>[key(g),g]));games=keys.map(k=>map.get(k)).filter(Boolean);render()}
  function applySavedOrder(catalog,orders){const rank=new Map();for(const x of orders||[]){const k=String(x?.game_key||'').trim(),n=Number(x?.sort_order);if(k&&Number.isFinite(n)&&!rank.has(k))rank.set(k,n)}const ranked=catalog.filter(g=>rank.has(key(g))).sort((a,b)=>rank.get(key(a))-rank.get(key(b))||catalog.indexOf(a)-catalog.indexOf(b));const fresh=catalog.filter(g=>!rank.has(key(g)));const ordered=[...ranked,...fresh];const students=ordered.filter(isStudentGame),platform=ordered.filter(g=>!isStudentGame(g));return [...students,...platform]}
  async function load(){setStatus('🔄 Sincronizando catálogo…','pending');try{const r=await fetch(`../../data/games.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error('No se pudo cargar games.json');const data=await r.json();let catalog=mergeUnique((data||[]).filter(g=>g?.url&&!isEvent(g)),BUILTIN_GAMES);try{const {data:rows,error}=await db.from('tecnomath_game_submissions').select('id,name,description,category,icon,image_url,source_type,game_url,status,published_url,published_path,author_name,author_email,created_at,published_at').in('status',['approved','published']).order('published_at',{ascending:true});if(error)throw error;catalog=mergeUnique(catalog,(rows||[]).map(submissionToGame).filter(Boolean))}catch(e){console.warn('No se pudieron cargar juegos de usuarios:',e.message)}original=[...catalog];const {data:orders,error}=await db.from('tecnomath_game_catalog_order').select('game_key,sort_order').order('sort_order',{ascending:true}).order('game_key',{ascending:true});if(error)throw error;games=applySavedOrder(original,orders);history=[];render();const students=games.filter(isStudentGame).length;setStatus(`✅ ${games.length} juegos sincronizados · 🎓 ${students} de estudiantes al principio.`,'ok')}catch(e){setStatus('❌ '+esc(e.message),'error')}}
  async function save(){if(saving)return;const changed=games.map(key).join('|')!==original.map(key).join('|');if(!changed)return;saving=true;markChanged();setStatus('💾 Guardando orden…','pending');try{const payload=games.map((g,i)=>({game_key:key(g),sort_order:i+1}));const {error}=await db.rpc('tecnomath_update_game_catalog_order',{p_orders:payload});if(error)throw error;await load();setStatus('✅ Orden guardado y sincronizado con el index.','ok')}catch(e){setStatus('❌ No se pudo guardar: '+esc(e.message),'error')}finally{saving=false;markChanged()}}
  window.TecnoMathGameOrder={init:async()=>{try{db=await auth.getClient();const user=await auth.currentUser();if(!user||!(await auth.isAdmin())){location.href='../../pages/auth.html';return}$('save').addEventListener('click',save);$('reload').addEventListener('click',load);$('search').addEventListener('input',render);$('undo').addEventListener('click',undo);$('reset').addEventListener('click',()=>{if(saving)return;history.push(snapshot());games=[...original];render();setStatus('↺ Orden original preparado. Pulsa Guardar para aplicarlo.','pending')});await load()}catch(e){setStatus('❌ '+esc(e.message),'error')}}};
})();
