importScripts('https://storage.googleapis.com/workbox-cdn/releases/5.1.2/workbox-sw.js');

// v15 — motor global de temáticas + Amor & Amistad.
const CACHE_NAME='tecnomath-offline-v15';
const OFFLINE_FALLBACK_PAGE='/index.html';
const PRECACHE_ASSETS=['/','/index.html','/js/shared.js','/js/firebase-config.js','/js/admin-guard.js','/js/theme-sync.js?v=15','/js/event-theme-guard.js?v=15','/css/amor-amistad.css?v=4','/css/admin.css','/manifest.json','/pages/auth.html','/pages/admin/index.html','/pages/game.html','/pages/eco-collector.html','/pages/animalandia.html','/pages/ods-2048.html','/pages/coral-guardian.html','/pages/eco-barrio.html','/pages/emoji-math.html','/img/icon-192.png','/img/icon-512.png'];
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE_NAME).then(c=>c.addAll(PRECACHE_ASSETS).catch(err=>console.warn('Precaché parcial:',err))));self.skipWaiting()});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(names=>Promise.all(names.filter(n=>n!==CACHE_NAME).map(n=>caches.delete(n)))));self.clients.claim()});
if(workbox.navigationPreload&&workbox.navigationPreload.isSupported())workbox.navigationPreload.enable();
async function injectThemeScripts(response){if(!response||!response.ok)return response;const type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;try{const html=await response.text();let out=html;if(!out.includes('/js/theme-sync.js'))out=out.replace(/<\/body>/i,'<script src="/js/theme-sync.js?v=15"></script></body>');if(!out.includes('/js/event-theme-guard.js'))out=out.replace(/<\/body>/i,'<script src="/js/event-theme-guard.js?v=15"></script></body>');const h=new Headers(response.headers);h.set('content-type','text/html; charset=utf-8');return new Response(out,{status:response.status,statusText:response.statusText,headers:h})}catch(_){return response}}
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;e.respondWith((async()=>{try{const network=await fetch(e.request);const response=await injectThemeScripts(network);if(response&&response.status===200){const cache=await caches.open(CACHE_NAME);await cache.put(e.request,response.clone())}return response}catch(_){let cached=await caches.match(e.request);if(cached)return injectThemeScripts(cached);if(e.request.mode==='navigate'){cached=await caches.match(OFFLINE_FALLBACK_PAGE);if(cached)return injectThemeScripts(cached)}return new Response('Sin conexión',{status:503})}})())});
self.addEventListener('sync',e=>{if(e.tag==='sync-tecnomath')e.waitUntil(self.clients.matchAll().then(cs=>cs.forEach(c=>c.postMessage({type:'background-sync',tag:e.tag}))));
self.addEventListener('periodicsync',e=>{if(e.tag==='periodic-tecnomath')e.waitUntil(self.clients.matchAll().then(cs=>cs.forEach(c=>c.postMessage({type:'periodic-sync',tag:e.tag}))));
self.addEventListener('push',e=>{let d={title:'Tecnomath',body:'¡Nuevo minijuego disponible!',icon:'/img/icon-192.png'};if(e.data){try{d={...d,...e.data.json()}}catch(_){}}e.waitUntil(self.registration.showNotification(d.title,{body:d.body,icon:d.icon,badge:'/img/icon-96.png',vibrate:[200,100,200],data:{url:'/'}}))});
self.addEventListener('notificationclick',e=>{e.notification.close();e.waitUntil(self.clients.matchAll({type:'window'}).then(list=>{for(const c of list)if(c.url==='/'&&'focus'in c)return c.focus();if(self.clients.openWindow)return self.clients.openWindow('/')}))});
self.addEventListener('message',e=>{if(e.data?.type==='SKIP_WAITING')self.skipWaiting()});
