/* TecnoMath — Motor global de temáticas v4 · Supabase */
(function(){'use strict';
const THEMES={normal:{emoji:'📚',name:'Normal',colors:{bg:'#060610',card:'#0d0d1a',border:'#1a1a2e',text:'#fff',muted:'#aaa',cyan:'#00FFFF',pink:'#FF00FF',green:'#39FF14',yellow:'#FFE600',gold:'#FFD700'}},halloween:{emoji:'🎃',name:'Halloween',colors:{bg:'#10050a',card:'#1b0b16',border:'#5b1f49',text:'#fff4e6',muted:'#d8b9c8',cyan:'#ff7a00',pink:'#ff3d00',green:'#b6ff00',yellow:'#ff9f00',gold:'#ff6a00'}},navidad:{emoji:'🎄',name:'Navidad',colors:{bg:'#06120d',card:'#0c2118',border:'#1e5b3b',text:'#fff',muted:'#b9d8c6',cyan:'#65e6ff',pink:'#ff3b5c',green:'#39ff7a',yellow:'#ffe66d',gold:'#ffd700'}},verano:{emoji:'☀️',name:'Verano',colors:{bg:'#071827',card:'#0c2438',border:'#1f6285',text:'#fff',muted:'#b7d1df',cyan:'#29d9ff',pink:'#ff5ea8',green:'#70ff9a',yellow:'#ffe66d',gold:'#ffd166'}},mundial:{emoji:'🏆',name:'Mundial',colors:{bg:'#07100a',card:'#0e1d11',border:'#355b3a',text:'#fff',muted:'#bfd3c2',cyan:'#4de1ff',pink:'#e8c547',green:'#4cff70',yellow:'#ffe600',gold:'#ffd700'}},regreso:{emoji:'🎒',name:'Regreso a clases',colors:{bg:'#10100a',card:'#1c1c0e',border:'#5d5a24',text:'#fff',muted:'#d0d0b4',cyan:'#5fd7ff',pink:'#ff72b6',green:'#75ff75',yellow:'#ffe600',gold:'#ffcc33'}},cumpleanos:{emoji:'🥳',name:'Cumpleaños',colors:{bg:'#130b18',card:'#21102b',border:'#703c85',text:'#fff',muted:'#d7c6df',cyan:'#55eaff',pink:'#ff66cc',green:'#75ff8a',yellow:'#ffe66d',gold:'#ffd166'}},feria:{emoji:'🎡',name:'Feria',colors:{bg:'#130b08',card:'#24130d',border:'#78401f',text:'#fff5e8',muted:'#dcc6b5',cyan:'#39e8ff',pink:'#ff4f81',green:'#7dff5c',yellow:'#ffe04b',gold:'#ffc400'}},feriaplus:{emoji:'🔥',name:'Feria Plus',colors:{bg:'#160604',card:'#280b08',border:'#8b2919',text:'#fff2e8',muted:'#dfc1b7',cyan:'#4deaff',pink:'#ff3b30',green:'#8cff4d',yellow:'#ffd000',gold:'#ff9d00'}},primavera:{emoji:'🌸',name:'Primavera',colors:{bg:'#100b14',card:'#1e1220',border:'#6f3d68',text:'#fff5fb',muted:'#d9c8d6',cyan:'#66eaff',pink:'#ff72b6',green:'#7dff9b',yellow:'#ffe66d',gold:'#ffd166'}},espacio:{emoji:'🚀',name:'Espacio',colors:{bg:'#050611',card:'#0b1022',border:'#273b72',text:'#f3f6ff',muted:'#bfc8df',cyan:'#55eaff',pink:'#a76bff',green:'#65ffbf',yellow:'#ffe66d',gold:'#ffd166'}},ciencia:{emoji:'🔬',name:'Ciencia',colors:{bg:'#06100e',card:'#0c1c18',border:'#245b4d',text:'#effff9',muted:'#bfd9d0',cyan:'#4deaff',pink:'#ff65c7',green:'#63ff9a',yellow:'#eaff66',gold:'#ffd166'}},amoramistad:{emoji:'💖',name:'Amor & Amistad',colors:{bg:'#fff0f7',card:'#ffffff',border:'#ffb4d5',text:'#351329',muted:'#76556b',cyan:'#c026d3',pink:'#ff4f9a',green:'#10b981',yellow:'#d97706',gold:'#f59e0b'}}};
const KEY='tecnomath:tema-activo',CSS_ID='tecnomath-amor-amistad-css',CSS_URL='/css/amor-amistad.css?v=4';let listening=false;
const valid=id=>{id=String(id||'').trim().toLowerCase();return THEMES[id]?id:null};
function syncCss(id){let l=document.getElementById(CSS_ID);if(id==='amoramistad'){if(!l){l=document.createElement('link');l.id=CSS_ID;l.rel='stylesheet';document.head.appendChild(l)}l.href=CSS_URL}else if(l)l.remove()}
function decorations(on){let l=document.getElementById('aa-global-hearts');if(!on){if(l)l.remove();return}if(l)return;l=document.createElement('div');l.id='aa-global-hearts';l.className='aa-floating-hearts';l.setAttribute('aria-hidden','true');const h=['💗','💖','💕','💘','💝','💓','♥'];for(let i=0;i<20;i++){const x=document.createElement('span');x.className='aa-floating-heart';x.textContent=h[i%h.length];x.style.setProperty('--aa-left',`${(i*17+4)%100}%`);x.style.setProperty('--aa-size',`${15+(i%5)*6}px`);x.style.setProperty('--aa-duration',`${8+(i%6)}s`);x.style.setProperty('--aa-delay',`${-(i%9)}s`);x.style.setProperty('--aa-drift',`${i%2?35:-30}px`);l.appendChild(x)}document.body.appendChild(l)}
function apply(id,persist=true){id=valid(id)||'normal';const t=THEMES[id],c=t.colors,r=document.documentElement;Object.entries({'--theme-bg':c.bg,'--theme-card':c.card,'--theme-border':c.border,'--theme-text':c.text,'--theme-muted':c.muted,'--neon-cyan':c.cyan,'--neon-pink':c.pink,'--neon-green':c.green,'--neon-yellow':c.yellow,'--gold':c.gold,'--primary-color':c.pink,'--secondary-color':c.cyan,'--accent-color':c.gold}).forEach(([k,v])=>r.style.setProperty(k,v));r.dataset.tecnomathTheme=id;r.dataset.theme=id;if(document.body){document.body.dataset.tecnomathTheme=id;document.body.dataset.theme=id;document.body.classList.toggle('tema-amor-amistad',id==='amoramistad');decorations(id==='amoramistad')}syncCss(id);if(persist)try{localStorage.setItem(KEY,id)}catch(_){}document.title=`${t.emoji} TecnoMath · Plataforma Educativa Interactiva`;window.TecnomathTheme={id,name:t.name,emoji:t.emoji,colors:{...c},apply};window.dispatchEvent(new CustomEvent('tecnomath:themechange',{detail:{id,theme:t}}))}
function cached(){try{return valid(localStorage.getItem(KEY))}catch(_){return null}}
async function load(){let id=cached()||'normal';try{const a=window.TecnomathAuth;if(a){const {data,error}=await a.getClient().rpc('tecnomath_get_settings');if(!error&&data)id=valid(data.theme)||id}}catch(e){console.warn('TecnoMath: no se pudo cargar configuración Supabase',e)}apply(id,false)}
async function listen(){try{const a=window.TecnomathAuth;if(!a){setTimeout(listen,300);return}const db=a.getClient();if(listening)return;listening=true;db.channel('tecnomath-settings').on('postgres_changes',{event:'*',schema:'public',table:'tecnomath_settings'},()=>load()).subscribe()}catch(e){console.warn('TecnoMath: listener de configuración no disponible',e)}}
window.TecnomathThemes={list:()=>Object.keys(THEMES),get:id=>THEMES[valid(id)||'normal'],apply};
function start(){load();listen()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
