(function(){'use strict';
const CATALOG_URL='../data/games.json';const $=id=>document.getElementById(id);
const state={db:null,user:null,games:[],counts:new Map(),voted:new Set(),previousPositions:new Map(),initialized:false,channel:null};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const gid=g=>String(g.url||g.name||'').trim();const money=n=>Number(n||0).toLocaleString('es-CO');
const live=(k,t)=>{$('liveStatus').className='live-badge '+(k||'');$('liveStatus').innerHTML='<i></i> '+esc(t)};
const toast=(a,b)=>{const d=document.createElement('div');d.className='toast';d.innerHTML='<strong>'+esc(a)+'</strong><span>'+esc(b)+'</span>';$('toastRegion').appendChild(d);setTimeout(()=>d.remove(),4200)};
function sorted(){return state.games.map(g=>({...g,id:gid(g),votes:Number(state.counts.get(gid(g))||0)})).sort((a,b)=>b.votes-a.votes||a.name.localeCompare(b.name,'es'))}
function positions(rows){const m=new Map();rows.forEach((g,i)=>m.set(g.id,i+1));return m}
function movement(id,pos){if(!state.initialized)return['same','— SIN CAMBIO'];const old=state.previousPositions.get(id);if(!old||old===pos)return['same','— SIN CAMBIO'];return old>pos?['up','↑ SUBIÓ']:['down','↓ BAJÓ']}
function renderStats(rows){const total=rows.reduce((s,g)=>s+g.votes,0);$('totalGames').textContent=money(rows.length);$('totalVotes').textContent=money(total);$('leaderName').textContent=rows[0]?.name||'—';$('averageVotes').textContent=money(rows.length?Math.round(total/rows.length):0)}
function renderRanking(rows){if(!rows.length){$('rankingList').innerHTML='<div class="empty">No hay juegos disponibles para votar actualmente.</div>';return}const np=positions(rows);if(state.initialized){rows.forEach(g=>{const old=state.previousPositions.get(g.id),pos=np.get(g.id);if(old&&old>3&&pos<=3)toast('🎉 ¡'+g.name+' subió al TOP 3!','Ahora ocupa la posición #'+pos+'.');if(old&&old<=3&&pos>3)toast('📉 '+g.name+' salió del TOP 3','Ahora ocupa la posición #'+pos+'.')})}$('rankingList').innerHTML=rows.slice(0,10).map((g,i)=>{const mv=movement(g.id,i+1),med=i===0?'🥇':i===1?'🥈':i===2?'🥉':'#'+(i+1);return '<div class="rank-row '+(mv[0]!=='same'?'changed':'')+'"><div class="rank-pos">'+med+'</div><div class="rank-info"><strong>'+esc(g.name)+'</strong><small>'+esc(g.category||'otros')+' · '+money(g.votes)+' votos <span class="move '+mv[0]+'">'+mv[1]+'</span></small></div><div class="rank-votes">'+money(g.votes)+'</div></div>'}).join('');state.previousPositions=np}
function renderGames(){const q=$('search').value.trim().toLowerCase(),cat=$('categoryFilter').value,all=sorted(),max=Math.max(1,...all.map(g=>g.votes)),rows=all.filter(g=>(!q||String(g.name+' '+(g.desc||'')+' '+(g.category||'')).toLowerCase().includes(q))&&(cat==='all'||g.category===cat));if(!rows.length){$('gamesGrid').innerHTML='<div class="empty">No encontramos juegos con esos filtros.</div>';return}$('gamesGrid').innerHTML=rows.map(g=>{const pos=all.findIndex(x=>x.id===g.id)+1,pct=Math.round(g.votes/max*100),voted=state.voted.has(g.id),img=g.imageUrl?'<img src="../'+esc(g.imageUrl.replace(/^\.\//,''))+'" alt="Imagen de '+esc(g.name)+'" loading="lazy" onerror="this.style.display=\'none\'">':'<span class="game-fallback">'+esc(g.icon||'🎮')+'</span>';return '<article class="game-card top'+(pos<=3?pos:'0')+'"><span class="place">'+(pos<=3?['🥇','🥈','🥉'][pos-1]:'#'+pos)+'</span><div class="game-thumb">'+img+'</div><h3 class="game-title">'+esc(g.name)+'</h3><p class="game-desc">'+esc(g.desc||g.description||'Juego educativo de TecnoMath.')+'</p><div class="meta-line"><span>❤️ '+money(g.votes)+' votos</span><span>'+pct+'%</span></div><div class="bar"><span style="width:'+pct+'%"></span></div><div class="card-actions"><button class="vote-btn" data-vote="'+esc(g.id)+'" '+(voted?'disabled':'')+'>'+(voted?'✓ VOTO REGISTRADO':'❤️ VOTAR')+'</button><a class="play-btn" href="'+esc(g.url)+'">🎮 JUGAR</a></div></article>'}).join('')}
async function loadCatalog(){const r=await fetch(CATALOG_URL+'?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('No se pudo cargar el catálogo.');const data=await r.json();if(!Array.isArray(data))throw Error('Catálogo inválido.');state.games=data.filter(g=>g&&g.name&&g.url);const cats=[...new Set(state.games.map(g=>g.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));$('categoryFilter').innerHTML='<option value="all">Todas las categorías</option>'+cats.map(c=>'<option value="'+esc(c)+'">'+esc(c)+'</option>').join('')}
async function loadCounts(){const r=await state.db.rpc('tecnomath_get_vote_counts');if(r.error)throw r.error;state.counts=new Map((r.data||[]).map(x=>[String(x.game_id),Number(x.votes||0)]))}
async function loadMyVotes(){if(!state.user)return;const r=await state.db.rpc('tecnomath_get_my_votes');if(r.error)throw r.error;state.voted=new Set((r.data||[]).map(x=>String(x.game_id)))}
async function render(){$('rankStatus').textContent='En vivo · '+new Date().toLocaleTimeString('es-CO',{hour:'2-digit',minute:'2-digit'});const r=sorted();renderStats(r);renderRanking(r);renderGames()}
async function vote(id,b){if(!state.user){toast('🔐 Inicia sesión','Necesitas una cuenta de TecnoMath para votar de forma segura.');return}if(state.voted.has(id))return;b.disabled=true;try{const r=await state.db.from('game_votes').insert({game_id:id,voter_id:state.user.id});if(r.error){if(r.error.code==='23505'||/duplicate|unique/i.test(r.error.message||'')){state.voted.add(id);b.textContent='✓ VOTO REGISTRADO';toast('✓ Ya habías votado','Ese juego ya tiene tu voto.');return}throw r.error}state.voted.add(id);state.counts.set(id,Number(state.counts.get(id)||0)+1);await render();toast('❤️ Voto registrado','El ranking se actualizó.')}catch(e){console.error('TecnoMath voting:',e);b.disabled=false;toast('⚠️ No se pudo registrar','Inténtalo nuevamente.')}}
async function subscribe(){if(state.channel)await state.db.removeChannel(state.channel);await state.db.realtime.setAuth();state.channel=state.db.channel('tecnomath-voting',{config:{private:true}}).on('broadcast',{event:'VOTE'},p=>{const id=String(p?.payload?.game_id||'');if(!id)return;state.counts.set(id,Number(state.counts.get(id)||0)+1);render()}).subscribe(s=>{if(s==='SUBSCRIBED')live('','VOTACIONES EN VIVO');else if(['CHANNEL_ERROR','TIMED_OUT','CLOSED'].includes(s))live('warn','RECONECTANDO…')})}
function bind(){$('search').addEventListener('input',renderGames);$('categoryFilter').addEventListener('change',renderGames);$('refreshBtn').addEventListener('click',async()=>{try{await loadCounts();await render();toast('↻ Actualizado','Datos sincronizados con Supabase.')}catch(e){console.error(e);toast('⚠️ Error','No pudimos actualizar las votaciones.')}});$('gamesGrid').addEventListener('click',e=>{const b=e.target.closest('[data-vote]');if(b)vote(b.dataset.vote,b)});window.addEventListener('beforeunload',()=>state.channel&&state.db.removeChannel(state.channel))}
async function boot(){try{$('rankingList').innerHTML=Array.from({length:6},()=>'<div class="skeleton"></div>').join('');$('gamesGrid').innerHTML=Array.from({length:6},()=>'<div class="skeleton"></div>').join('');await loadCatalog();state.db=await TecnomathAuth.getClient();state.user=await TecnomathAuth.currentUser();if(!state.user)$('gamesGrid').insertAdjacentHTML('beforebegin','<div class="login-note">🔐 Puedes consultar el ranking sin iniciar sesión. Para votar, inicia sesión en <a href="auth.html" style="color:#00f5ff">TecnoMath</a>.</div>');await loadCounts();await loadMyVotes();bind();await render();await subscribe();state.initialized=true;await render()}catch(e){console.error(e);live('error','ERROR DE CONEXIÓN');$('rankingList').innerHTML='<div class="empty">⚠️ No pudimos cargar las votaciones. <button class="ghost-btn" onclick="location.reload()">Reintentar</button></div>'}}
boot();})();