const $=id=>document.getElementById(id);let playing=false,round=0,score=0,lives=3,combo=0,best=0,time=90,q=null,enemyHP=100,enemyMax=100,playerHP=100,questionTimer=null,shield=false,critical=false,sessionCorrect=0,sessionWrong=0,powers={double:1,shield:1,steal:1,time:1};
const enemies=[['🤖','ROBO-CALCULUS','Cálculo',100,18],['👹','MATH DEMON','Operaciones',115,20],['👽','ALIEN X','Números',125,22],['🧙','MATH WIZARD','Álgebra',135,24],['🐉','DRAGÓN FRACTAL','Geometría',150,26],['🧟','ZOMBIE RAÍZ','Raíces',165,28],['⚔️','CABALLERO PRIMO','Aritmética',180,30],['🦂','ESCORPIÓN LOGARÍTMICO','Potencias',195,32],['🤖','TITÁN BINARIO','Lógica',210,34],['👾','NÚCLEO CAÓTICO','Desafío',225,36]];
const bosses=[['👑','REY DEL CÁLCULO','Maestro de las operaciones',260,38],['🐲','DRAGÓN INFINITO','Señor de las potencias',320,44],['🌌','SEÑOR DEL INFINITO','Jefe final definitivo',400,52]];
const bank=[['25² = ?',['625','525','650','600'],0,'25 × 25 = 625'],['12 × 8 = ?',['86','96','108','88'],1,'12 grupos de 8 dan 96'],['144 ÷ 12 = ?',['10','11','12','14'],2,'12 × 12 = 144'],['3x + 6 = 18 → x = ?',['3','4','5','6'],1,'3x = 12, por eso x = 4'],['17 + 28 = ?',['35','45','55','46'],1,'17 + 28 = 45'],['9 × 7 = ?',['56','63','72','67'],1,'9 × 7 = 63'],['81 ÷ 9 = ?',['7','8','9','10'],2,'9 × 9 = 81'],['15² = ?',['215','225','235','250'],1,'15 × 15 = 225'],['√144 = ?',['10','11','12','14'],2,'12 × 12 = 144'],['2³ × 3 = ?',['18','24','12','16'],1,'8 × 3 = 24'],['5x - 10 = 15 → x = ?',['3','4','5','6'],2,'5x = 25, por eso x = 5'],['36% de 50 = ?',['16','18','20','22'],1,'0.36 × 50 = 18'],['3/4 + 1/4 = ?',['1/2','1','3/4','2'],1,'Cuatro cuartos forman 1'],['7² - 5² = ?',['12','24','25','49'],1,'49 - 25 = 24'],['2⁵ = ?',['16','24','32','64'],2,'2 × 2 × 2 × 2 × 2 = 32'],['√225 = ?',['12','15','18','20'],1,'15 × 15 = 225']];
function shuffle(a){return[...a].sort(()=>Math.random()-.5)}
function readImage(key){try{return localStorage.getItem('jinete11_'+key)||''}catch(e){return''}}
function applyCustomImages(){const bg=readImage('background'),player=readImage('player'),enemy=readImage('enemy');document.body.classList.toggle('customBackground',!!bg);if(bg)document.body.style.setProperty('--custom-bg',`url("${bg}")`);else document.body.style.removeProperty('--custom-bg');['playerPortrait','playerCharacter'].forEach(id=>{const el=$(id);if(el){el.style.backgroundImage=player?`url("${player}")`:'';el.classList.toggle('imageCharacter',!!player);if(player&&id==='playerCharacter')el.textContent=''}});['enemyPortrait','enemyCharacter'].forEach(id=>{const el=$(id);if(el){el.style.backgroundImage=enemy?`url("${enemy}")`:'';el.classList.toggle('imageCharacter',!!enemy);if(enemy&&id==='enemyCharacter')el.textContent=''}})}
function saveImage(input,key){const file=input.files&&input.files[0];if(!file)return;if(file.size>3*1024*1024){alert('La imagen debe pesar menos de 3 MB.');input.value='';return}const reader=new FileReader();reader.onload=()=>{try{localStorage.setItem('jinete11_'+key,reader.result);applyCustomImages();setLog('🖼️ Imagen personalizada aplicada.')}catch(e){alert('No se pudo guardar la imagen. Prueba una imagen más pequeña.')}};reader.readAsDataURL(file)}
function setupCustomization(){$('customizeBtn').onclick=()=>{$('customPanel').classList.toggle('hidden')};$('bgImage').onchange=()=>saveImage($('bgImage'),'background');$('playerImage').onchange=()=>saveImage($('playerImage'),'player');$('enemyImage').onchange=()=>saveImage($('enemyImage'),'enemy');$('clearImages').onclick=()=>{['background','player','enemy'].forEach(k=>localStorage.removeItem('jinete11_'+k));['bgImage','playerImage','enemyImage'].forEach(id=>$(id).value='');applyCustomImages()}}
function syncProgress(){if(!window.TecnoMathProgress)return;const p=TecnoMathProgress.read();$('globalLevel').textContent=p.level;$('playerLevel').textContent=p.level}function update(){lives=Math.ceil(Math.max(0,playerHP)/34);$('lives').textContent=lives;$('score').textContent=score;$('combo').textContent=combo;$('time').textContent=time;$('playerHP').style.width=Math.max(0,playerHP)+'%';$('enemyHP').style.width=Math.max(0,enemyHP/enemyMax*100)+'%';$('playerHPText').textContent=Math.round(playerHP)+' HP';$('enemyHPText').textContent=Math.round(enemyHP)+' HP';$('round').textContent='RONDA '+Math.min(round+1,30)+' / 30';$('streak').textContent='🔥 COMBO '+combo;syncProgress()}
function setLog(t){$('battleLog').textContent=t}function getEnemy(){if(round===9)return bosses[0];if(round===19)return bosses[1];if(round===29)return bosses[2];return enemies[Math.min(enemies.length-1,Math.floor(round/3))]}
function newQuestion(){if(!playing)return;const base=bank[Math.floor(Math.random()*bank.length)],opts=shuffle(base[1]);q={text:base[0],correct:base[1][base[2]],opts,tip:base[3]};const e=getEnemy();enemyMax=e[3];$('enemyName').textContent=e[0]+' '+e[1];if(!readImage('enemy')){$('enemyPortrait').textContent=e[0];$('enemyCharacter').textContent=e[0]}$('category').textContent=e[2];$('question').textContent=q.text;$('answers').innerHTML=q.opts.map((v,i)=>`<button data-i="${i}">${v}</button>`).join('');document.querySelectorAll('#answers button').forEach(b=>b.onclick=()=>answer(+b.dataset.i));setLog(round===9||round===19||round===29?'⚠️ ¡JEFE FINAL! Prepárate para un desafío especial.':'Piensa la operación y elige la respuesta correcta.');clearInterval(questionTimer);let left=Math.max(5.5,8-round*.07);questionTimer=setInterval(()=>{left-=.1;$('questionBar').style.width=Math.max(0,left/8*100)+'%';if(left<=0){clearInterval(questionTimer);answer(-1)}},100)}
function animateAttack(a,d){const x=$(a==='player'?'playerSprite':'enemySprite');x.classList.remove('attack');void x.offsetWidth;x.classList.add('attack');setTimeout(()=>{$('damage').textContent='-'+d},250);setTimeout(()=>x.classList.remove('attack'),700)}
function answer(i){if(!playing||!q)return;clearInterval(questionTimer);const bs=[...document.querySelectorAll('#answers button')];bs.forEach(b=>b.disabled=true);const ok=i>=0&&q.opts[i]===q.correct;if(i>=0&&bs[i])bs[i].classList.add(ok?'correct':'wrong');if(ok){sessionCorrect++;combo++;best=Math.max(best,combo);let d=14+Math.min(combo,8)*3;if(critical){d*=2;critical=false}enemyHP=Math.max(0,enemyHP-d);score+=100+d*5+combo*15;animateAttack('player',d);setLog('¡Correcto! '+q.tip);if(enemyHP<=0){const boss=round===9||round===19||round===29;score+=boss?1500:500;round++;update();setTimeout(()=>round>=30?win():nextEnemy(boss),950);return}}else{sessionWrong++;combo=0;if(shield){shield=false;setLog('🛡️ ¡Escudo! Ataque bloqueado.')}else{const e=getEnemy(),d=e[4]||20;playerHP=Math.max(0,playerHP-d);animateAttack('enemy',d);setLog(i===-1?'⏳ Tiempo agotado. '+q.tip:'Incorrecto. 💡 '+q.tip);if(playerHP<=0){update();setTimeout(lose,950);return}}}update();setTimeout(newQuestion,1100)}
function nextEnemy(wasBoss){const e=getEnemy();enemyHP=enemyMax=e[3];playerHP=Math.min(100,playerHP+(wasBoss?25:12));if(wasBoss){time+=10;setLog('👑 ¡JEFE DERROTADO! +25 HP y +10 segundos.')}else setLog('🏆 Rival derrotado. +12 HP.');update();setTimeout(newQuestion,900)}
function usePower(t){if(!playing||!powers[t])return;powers[t]--;document.querySelector(`[data-power="${t}"]`).disabled=true;if(t==='double'){critical=true;setLog('⚡ Próximo acierto: daño x2')}if(t==='shield'){shield=true;setLog('🛡️ Escudo preparado')}if(t==='steal'){const w=[...document.querySelectorAll('#answers button')].filter((b,i)=>q.opts[i]!==q.correct);if(w.length)w[0].remove();setLog('💡 Se eliminó una opción incorrecta')}if(t==='time'){time+=8;setLog('⏱️ +8 segundos')}update()}
function start(){playing=true;round=score=combo=best=sessionCorrect=sessionWrong=0;lives=3;time=90;enemyHP=playerHP=100;enemyMax=100;shield=critical=false;Object.keys(powers).forEach(k=>powers[k]=1);document.querySelectorAll('[data-power]').forEach(b=>b.disabled=false);$('menu').classList.add('hidden');$('result').classList.add('hidden');$('battle').classList.remove('hidden');applyCustomImages();update();newQuestion();clearInterval(window.mainTimer);window.mainTimer=setInterval(()=>{if(--time<=0)lose();update()},1000)}
function finish(winState){if(!playing)return;playing=false;clearInterval(questionTimer);clearInterval(window.mainTimer);if(window.TecnoMathProgress)TecnoMathProgress.record({games:1,correct:sessionCorrect,wrong:sessionWrong,xp:sessionCorrect*25+(winState?500:0),coins:sessionCorrect*5+(winState?80:0),topic:'Matemáticas'});syncProgress();$('battle').classList.add('hidden');$('result').classList.remove('hidden');$('resultIcon').textContent=winState?'🏆':'🧠';$('resultTitle').textContent=winState?'¡CAMPEÓN DE LOS 30 NIVELES!':'¡SIGUE ENTRENANDO!';$('resultText').textContent=winState?'Derrotaste a los 3 jefes finales y completaste la campaña.':'Tus resultados fueron guardados para mejorar tu progreso global.';$('resultStats').innerHTML=`🏆 ${score} puntos<br>⭐ ${sessionCorrect*25+(winState?500:0)} XP ganada<br>🪙 ${sessionCorrect*5+(winState?80:0)} monedas<br>🎯 ${sessionCorrect} correctas · ${sessionWrong} errores<br>🔥 Mejor combo: ${best}`}function win(){finish(true)}function lose(){finish(false)}
$('start').onclick=start;$('again').onclick=start;document.querySelectorAll('[data-power]').forEach(b=>b.onclick=()=>usePower(b.dataset.power));setupCustomization();applyCustomImages();update();window.addEventListener('tecnomath:progress',syncProgress);