const $=id=>document.getElementById(id);
const S={cat:"matematicas",diff:"facil",qs:[],q:null,used:new Set(),round:0,score:0,ok:0,bad:0,streak:0,lives:3,p:0,r1:0,r2:0,locked:false,started:0};
const CFG={facil:{adv:15,pen:5,rv:[.55,.67]},normal:{adv:13,pen:6,rv:[.72,.82]},dificil:{adv:11,pen:8,rv:[.9,1.0]}};
const CAT={matematicas:"🔴 MATEMÁTICAS",espanol:"🔵 ESPAÑOL",sociales:"🟡 SOCIALES",aleatorio:"🎲 ALEATORIO"};
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function screen(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");$("topHud").hidden=id!=="race";scrollTo(0,0)}
function modal(id,on){$(id).classList.toggle("open",on)}
async function load(){if(S.qs.length)return;const r=await fetch("data/questions.json",{cache:"no-store"});if(!r.ok)throw Error("questions");S.qs=await r.json();if(!Array.isArray(S.qs)||S.qs.length<12)throw Error("empty")}
function pool(){let p=S.qs.filter(q=>S.cat==="aleatorio"||q.category===S.cat);let d=p.filter(q=>q.difficulty===S.diff);return d.length>=4?d:p}
function nextQ(){let p=pool(),a=p.filter(q=>!S.used.has(q.question));if(!a.length){S.used.clear();a=p}S.q=a[Math.floor(Math.random()*a.length)];S.used.add(S.q.question);$("qnum").textContent="Pregunta "+(S.round+1);$("q").textContent=S.q.question;$("qcat").textContent=CAT[S.q.category];$("answers").innerHTML="";$("feedback").textContent="";$("feedback").className="feedback";shuffle(S.q.options.map((x,i)=>({x,i}))).forEach(o=>{let b=document.createElement("button");b.className="answer";b.textContent=o.x;b.onclick=()=>answer(o.i,b);$("answers").appendChild(b)})}
function hud(){ $("miniProgress").textContent=Math.round(S.p)+"%";$("miniLives").textContent="❤️".repeat(S.lives)||"0";$("miniScore").textContent=S.score;$("ok").textContent=S.ok;$("bad").textContent=S.bad;$("streak").textContent=S.streak?"x"+Math.min(4,S.streak):"0";$("score").textContent=S.score;$("bar").style.width=S.p+"%";$("p").style.left=(8+S.p*.78)+"%";$("r1").style.left=(8+S.r1*.78)+"%";$("r2").style.left=(8+S.r2*.78)+"%"}
function answer(i,b){if(S.locked)return;S.locked=true;document.querySelectorAll(".answer").forEach(x=>x.disabled=true);let yes=i===S.q.correct;if(yes){S.ok++;S.streak++;let mult=Math.min(4,S.streak);let pts=100+(mult>=2?50*mult:0);S.score+=pts;S.p=Math.min(100,S.p+CFG[S.diff].adv+(mult-1));b.classList.add("correct");$("feedback").className="feedback ok";$("feedback").textContent="¡CORRECTO! 🐔💨 +"+pts+" puntos · ¡racha x"+mult+"!";$("trackmsg").textContent="🐔 ¡Tu pollito acelera!";$("p").classList.add("run");setTimeout(()=>$("p").classList.remove("run"),700)}else{S.bad++;S.streak=0;S.lives=Math.max(0,S.lives-1);S.p=Math.max(0,S.p-CFG[S.diff].pen);b.classList.add("wrong");document.querySelectorAll(".answer").forEach((x,n)=>{if(n===S.q.correct)x.classList.add("correct")});$("feedback").className="feedback bad";$("feedback").textContent="¡INCORRECTO! 😵 Correcta: "+S.q.options[S.q.correct];$("trackmsg").textContent="💥 Pierdes distancia, pero sigues en carrera.";$("p").classList.add("hit");setTimeout(()=>$("p").classList.remove("hit"),500)}hud();if(S.p>=100){finish();return}setTimeout(()=>{S.round++;S.locked=false;nextQ()},1000)}
let timer;
function rivals(){if(S.locked||!S.started)return;let c=CFG[S.diff],t=(Date.now()-S.started)/1000;S.r1=Math.min(99,S.r1+c.rv[0]*(1+Math.sin(t*.7)*.15));S.r2=Math.min(99,S.r2+c.rv[1]*(1+Math.cos(t*.55)*.12));hud()}
function finish(){clearInterval(timer);S.locked=true;let arr=[S.p,S.r1,S.r2].sort((a,b)=>b-a),pos=arr.indexOf(S.p)+1;let bonus=pos===1?300:pos===2?150:50;S.score+=bonus;save(pos);$("resultTitle").textContent=pos===1?"🏆 ¡LLEGASTE A LA META!":pos===2?"🥈 ¡SEGUNDO LUGAR!":"🐔 ¡CARRERA TERMINADA!";$("resultSub").textContent=pos===1?"¡Excelente trabajo! Tu pollito ganó la carrera.":"¡Buen intento! Sigue practicando.";$("pos").textContent=pos+".º";$("resOk").textContent=S.ok;$("resBad").textContent=S.bad;$("resScore").textContent=S.score;screen("result")}
function save(pos){let a=JSON.parse(localStorage.getItem("pollitoRaceRecords")||"[]");a.push({score:S.score,pos,ok:S.ok,bad:S.bad,cat:CAT[S.cat],diff:S.diff,date:new Date().toLocaleDateString("es-CO")});a.sort((x,y)=>y.score-x.score);localStorage.setItem("pollitoRaceRecords",JSON.stringify(a.slice(0,8)))}
function records(){let a=JSON.parse(localStorage.getItem("pollitoRaceRecords")||"[]");$("recordsList").innerHTML=a.length?a.map((r,i)=>'<div class="record"><span>#'+(i+1)+' '+r.cat+'<small>'+r.diff+' · '+r.ok+' correctas · '+r.date+'</small></span><b>'+r.score+' pts</b></div>').join(""):'<p style="color:#8f98a8">Todavía no hay récords.</p>'}
async function start(){try{await load();S.used.clear();S.round=0;S.score=0;S.ok=0;S.bad=0;S.streak=0;S.lives=3;S.p=0;S.r1=0;S.r2=0;S.locked=false;S.started=Date.now();$("raceCat").textContent=CAT[S.cat];screen("race");hud();nextQ();clearInterval(timer);timer=setInterval(rivals,500)}catch(e){console.error(e);alert("No se pudo cargar data/questions.json")}}
document.querySelectorAll("[data-cat]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-cat]").forEach(x=>x.classList.remove("active"));b.classList.add("active");S.cat=b.dataset.cat;$("selection").textContent=CAT[S.cat]+" · "+S.diff.toUpperCase()+" · 3 carriles · 4 opciones"});
document.querySelectorAll("[data-diff]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-diff]").forEach(x=>x.classList.remove("active"));b.classList.add("active");S.diff=b.dataset.diff;$("selection").textContent=CAT[S.cat]+" · "+S.diff.toUpperCase()+" · 3 carriles · 4 opciones"});
$("play").onclick=$("categories").onclick=()=>screen("setup");$("start").onclick=start;$("back").onclick=()=>screen("home");$("home").onclick=()=>screen("home");$("again").onclick=()=>screen("setup");$("clear").onclick=()=>{localStorage.removeItem("pollitoRaceRecords");records()};$("selection").textContent=CAT[S.cat]+" · FÁCIL · 3 carriles · 4 opciones";
document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>{modal(b.dataset.open,true);if(b.dataset.open==="records")records()});document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>modal(b.dataset.close,false));document.querySelectorAll(".modal").forEach(m=>m.onclick=e=>{if(e.target===m)modal(m.id,false)});
