(()=>{"use strict";
const D=window.MATHVERSE_DATA;const canvas=document.getElementById("world"),ctx=canvas.getContext("2d");const W=1280,H=720;
const state={x:160,y:520,speed:3.2,energy:0,xp:0,level:1,attempts:{},solved:{},hints:{},inventory:["variable-scanner"],coins:0,events:[],active:null,paused:false,completed:false,saveTimer:null};
let keys=new Set(),last=performance.now(),near=null,toasts=[];
const $=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function loadLocal(){try{return JSON.parse(localStorage.getItem("mathverse_state")||"null")}catch(_){return null}}
function applyProgress(p){if(!p)return;Object.assign(state,{x:Number(p.x??state.x),y:Number(p.y??state.y),energy:Number(p.energy||0),xp:Number(p.xp||0),level:Number(p.level||1),attempts:p.attempts||{},solved:p.solved||{},hints:p.hints||{},inventory:Array.isArray(p.inventory)?p.inventory:["variable-scanner"],coins:Number(p.coins||0),events:Array.isArray(p.events)?p.events:[]});}
async function restore(){let p=loadLocal();if(window.TecnoMathProgress?.restore){try{const cloud=await window.TecnoMathProgress.restore("mathverse");if(cloud&&Object.keys(cloud).length)p=cloud}catch(e){console.warn("Mathverse restore:",e)}}applyProgress(p);renderUI();setSave("Progreso restaurado");}
function snapshot(){return{version:1,x:state.x,y:state.y,energy:state.energy,xp:state.xp,level:state.level,attempts:state.attempts,solved:state.solved,hints:state.hints,inventory:state.inventory,coins:state.coins,events:state.events,zone:"city-of-variables",updatedAt:new Date().toISOString()}}
function save(){const p=snapshot();try{localStorage.setItem("mathverse_state",JSON.stringify(p))}catch(_){};if(window.TecnoMathProgress?.save)window.TecnoMathProgress.save("mathverse",p).then(()=>setSave("● Guardado en Supabase")).catch(()=>setSave("● Guardado local; sincronización pendiente"));else setSave("● Guardado local")}
function scheduleSave(){clearTimeout(state.saveTimer);state.saveTimer=setTimeout(save,450)}
function setSave(t){$("saveStatus").textContent=t}
function event(type,data={}){state.events.push({type,...data,t:new Date().toISOString()});if(state.events.length>150)state.events.shift();scheduleSave()}
function xpForLevel(n){return Math.round(45*Math.pow(n-1,1.35))}
function refreshLevel(){let old=state.level;while(state.level<100&&state.xp>=xpForLevel(state.level+1))state.level++;if(state.level>old)toast("⬆️ NIVEL "+state.level+" · "+levelName(state.level));}
function levelName(l){let name="Explorador";for(const x of D.levels)if(l>=x.level)name=x.name;return name}
function addXP(v,reason){state.xp+=v;refreshLevel();toast("+"+v+" XP · "+reason);event("xp_gained",{value:v,reason});renderUI();scheduleSave()}
function toast(t){toasts.push(t);const el=$("toast");el.textContent=t;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),2200)}
function rectHit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
const objects=[
{id:"battery-alpha",x:260,y:450,w:90,h:90,label:"BATERÍA α",color:"#00eaff",type:"problem"},
{id:"lift-beta",x:560,y:270,w:100,h:150,label:"ASCENSOR β",color:"#ff31d2",type:"problem"},
{id:"generator-gamma",x:850,y:470,w:110,h:100,label:"GENERADOR γ",color:"#52ff9b",type:"problem"},
{id:"door-delta",x:1060,y:260,w:90,h:170,label:"PUERTA δ",color:"#ffd85a",type:"problem"},
{id:"bridge-epsilon",x:720,y:120,w:190,h:55,label:"PUENTE ε",color:"#9d7cff",type:"problem"}
];
const walls=[{x:0,y:0,w:1280,h:28},{x:0,y:692,w:1280,h:28},{x:0,y:0,w:28,h:720},{x:1252,y:0,w:28,h:720},{x:430,y:28,w:30,h:330},{x:930,y:390,w:30,h:302}];
function problemBy(id){return D.problems.find(p=>p.id===id)}
function objectLocked(o){return !state.solved[o.id]&&o.id!=="battery-alpha"}
function playerBox(){return{x:state.x-13,y:state.y-18,w:26,h:36}}
function move(dt){if(state.active||state.paused)return;let dx=0,dy=0;if(keys.has("ArrowLeft")||keys.has("a"))dx--;if(keys.has("ArrowRight")||keys.has("d"))dx++;if(keys.has("ArrowUp")||keys.has("w"))dy--;if(keys.has("ArrowDown")||keys.has("s"))dy++;if(!dx&&!dy)return;const len=Math.hypot(dx,dy)||1;dx=dx/len*state.speed*dt;dy=dy/len*state.speed*dt;const next={x:state.x+dx,y:state.y+dy};const box={x:next.x-13,y:next.y-18,w:26,h:36};if(!walls.some(w=>rectHit(box,w))) {state.x=clamp(next.x,45,W-45);state.y=clamp(next.y,50,H-45);scheduleSave()}}
function nearest(){let best=null,bd=9999;for(const o of objects){const d=Math.hypot(state.x-(o.x+o.w/2),state.y-(o.y+o.h/2));if(d<95&&d<bd){best=o;bd=d}}return best}
function drawGrid(){ctx.fillStyle="#080b16";ctx.fillRect(0,0,W,H);ctx.strokeStyle="#121a2c";ctx.lineWidth=1;for(let x=0;x<W;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.fillStyle="#0c1220";ctx.fillRect(30,30,400,330);ctx.fillRect(460,30,790,200);ctx.fillRect(30,380,400,310);ctx.fillStyle="#0e1724";ctx.fillRect(460,390,470,300);ctx.fillStyle="#10152b";ctx.fillRect(960,390,290,300)}
function glowRect(x,y,w,h,c){ctx.save();ctx.shadowColor=c;ctx.shadowBlur=18;ctx.fillStyle=c+"30";ctx.fillRect(x,y,w,h);ctx.shadowBlur=0;ctx.strokeStyle=c;ctx.strokeRect(x,y,w,h);ctx.restore()}
function drawObject(o){const solved=!!state.solved[o.id];ctx.save();if(solved)ctx.globalAlpha=.8;glowRect(o.x,o.y,o.w,o.h,o.color);ctx.fillStyle="#eaf4ff";ctx.font="bold 12px system-ui";ctx.textAlign="center";ctx.fillText(o.label,o.x+o.w/2,o.y+o.h+17);if(solved){ctx.fillStyle="#52ff9b";ctx.fillText("● ACTIVO",o.x+o.w/2,o.y-8)}else{ctx.fillStyle="#9ba7c2";ctx.fillText("∑ VARIABLE",o.x+o.w/2,o.y+o.h/2+4)}ctx.restore()}
function drawPlayer(){ctx.save();ctx.translate(state.x,state.y);ctx.shadowColor="#00eaff";ctx.shadowBlur=15;ctx.fillStyle="#00eaff";ctx.beginPath();ctx.arc(0,-11,10,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#16213a";ctx.fillRect(-13,-1,26,29);ctx.strokeStyle="#ff31d2";ctx.strokeRect(-13,-1,26,29);ctx.fillStyle="#ffd85a";ctx.fillRect(-5,7,10,7);ctx.restore()}
function drawNPC(){ctx.save();ctx.translate(140,180);ctx.fillStyle="#ff31d2";ctx.beginPath();ctx.arc(0,-18,12,0,Math.PI*2);ctx.fill();ctx.fillStyle="#273252";ctx.fillRect(-15,-5,30,42);ctx.fillStyle="#fff";ctx.font="11px system-ui";ctx.textAlign="center";ctx.fillText("NOVA · INGENIERA",0,57);ctx.restore()}
function drawPaths(){ctx.strokeStyle="#24304a";ctx.lineWidth=18;ctx.beginPath();ctx.moveTo(80,550);ctx.lineTo(390,550);ctx.lineTo(390,420);ctx.lineTo(800,420);ctx.lineTo(800,530);ctx.lineTo(1100,530);ctx.stroke();ctx.strokeStyle="#31415f";ctx.lineWidth=2;ctx.setLineDash([8,10]);ctx.beginPath();ctx.moveTo(80,550);ctx.lineTo(390,550);ctx.lineTo(390,420);ctx.lineTo(800,420);ctx.lineTo(800,530);ctx.lineTo(1100,530);ctx.stroke();ctx.setLineDash([])}
function draw(){drawGrid();drawPaths();walls.forEach(w=>{ctx.fillStyle="#151c2d";ctx.fillRect(w.x,w.y,w.w,w.h)});drawNPC();objects.forEach(drawObject);drawPlayer();if(near&&!state.active&&!state.paused){const dx=state.x-(near.x+near.w/2),dy=state.y-(near.y+near.h/2);ctx.strokeStyle="#fff";ctx.globalAlpha=.3;ctx.beginPath();ctx.arc(near.x+near.w/2,near.y+near.h/2,Math.min(58,Math.hypot(dx,dy)),0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1}}
function interact(){near=nearest();if(!near)return;const p=problemBy(near.id);if(state.solved[near.id]){toast("Sistema activo: "+p.effect.message);return}openProblem(p)}
function openProblem(p){state.active=p.id;const n=state.attempts[p.id]||0;$("problemTitle").textContent=p.title;$("problemStory").textContent=p.story;$("equation").textContent=p.equation;$("attempts").textContent="Intentos en este sistema: "+n;$("hint").textContent=state.hints[p.id]?p["hint"+Math.min(state.hints[p.id],3)]:"";$("feedback").textContent="";$("feedback").className="feedback";$("answer").value="";$("problemModal").classList.remove("hidden");setTimeout(()=>$("answer").focus(),50)}
function closeProblem(){state.active=null;$("problemModal").classList.add("hidden")}
function parseAnswer(v){let s=String(v||"").trim().replace(",",".").toLowerCase();if(!s)return NaN;if(s.includes("=")){const m=s.match(/(?:x\s*=\s*)?(-?\d+(?:\.\d+)?)/);if(m)return Number(m[1])}const n=Number(s);return Number.isFinite(n)?n:NaN}
function solve(){const p=problemBy(state.active);if(!p)return;const value=parseAnswer($("answer").value);const attempts=(state.attempts[p.id]||0)+1;state.attempts[p.id]=attempts;event("problem_attempted",{problemId:p.id,attempt:attempts,topic:p.topic});if(Number.isFinite(value)&&Math.abs(value-p.answer)<.00001){state.solved[p.id]=true;state.energy=clamp(state.energy+(p.effect.value||20),0,100);event("problem_solved",{problemId:p.id,attempt:attempts,topic:p.topic,hints:state.hints[p.id]||0});addXP(90+(state.hints[p.id]?10:25),"sistema activado");applyEffect(p);$("feedback").className="feedback ok";$("feedback").textContent="La solución encaja con el sistema. Observa lo que acaba de cambiar.";setTimeout(()=>{closeProblem();renderUI();checkFinish()},900)}else{event("problem_failed",{problemId:p.id,attempt:attempts,topic:p.topic});$("feedback").className="feedback try";if(attempts===1)$("feedback").textContent="La máquina no responde. Observa la relación entre las cantidades y vuelve a experimentar.";else if(attempts===2){state.hints[p.id]=Math.max(1,state.hints[p.id]||0);$("hint").textContent=p.hint1;$("feedback").textContent="La máquina deja una señal: hay una pista en el panel."}else{$("feedback").textContent="La relación todavía no encaja. Puedes pedir otra pista sin perder el progreso.";state.hints[p.id]=Math.min(3,(state.hints[p.id]||0)+1);$("hint").textContent=p["hint"+state.hints[p.id]]||p.hint3}renderUI();scheduleSave()}}
function hint(){const p=problemBy(state.active);if(!p)return;const n=Math.min(3,(state.hints[p.id]||0)+1);state.hints[p.id]=n;event("hint_used",{problemId:p.id,hint:n,topic:p.topic});$("hint").textContent=p["hint"+n];$("feedback").className="feedback info";$("feedback").textContent="La ciudad te da una pista, pero la solución sigue siendo tuya.";scheduleSave()}
function applyEffect(p){const t=p.effect.type;toast("⚡ "+p.effect.message);if(t==="elevator"){state.x=600;state.y=220}if(t==="door"){state.x=1030;state.y=470}if(t==="bridge"){}if(t==="generator"){}if(t==="energy"){}renderUI();scheduleSave()}
function checkFinish(){if(Object.keys(state.solved).length===D.problems.length&&!state.completed){state.completed=true;addXP(250,"zona completada");event("zone_unlocked",{zone:"circuito-vectorial",from:"city-of-variables"});$("finishModal").classList.remove("hidden")}}
function renderUI(){refreshLevel();$("level").textContent=state.level;$("xp").textContent=state.xp;const cur=xpForLevel(state.level),next=xpForLevel(state.level+1);$("xpBar").style.width=clamp(((state.xp-cur)/Math.max(1,next-cur))*100,0,100)+"%";$("energyBar").style.width=state.energy+"%";$("energyText").textContent=state.energy+" / 100";$("skillBar").style.width=clamp(Object.keys(state.solved).length/D.problems.length*100,0,100)+"%";$("worldStatus").textContent=Object.keys(state.solved).length===5?"Todos los sistemas de la ciudad están activos.":"Quedan "+(5-Object.keys(state.solved).length)+" sistemas matemáticos por activar.";$("problemList").innerHTML=D.problems.map(p=>'<div class="progress-row '+(state.solved[p.id]?"done":"")+'"><i></i><span>'+p.title+'</span></div>').join("");$("missionText").textContent=Object.keys(state.solved).length===5?"La red está restaurada. Explora el distrito.":"Explora, encuentra un sistema y usa las variables para cambiarlo."}
function inventory(){ $("inventoryGrid").innerHTML=D.tools.map(t=>'<div class="item"><b>'+t.icon+" "+t.name+'</b><span>'+t.desc+'</span></div>').join("");$("inventoryModal").classList.remove("hidden")}
function pause(){state.paused=true;$("pauseModal").classList.remove("hidden")}
function resume(){state.paused=false;$("pauseModal").classList.add("hidden");last=performance.now()}
function loop(now){const dt=Math.min(2,(now-last)/16.67);last=now;move(dt);near=nearest();$("interaction").classList.toggle("hidden",!near||state.active||state.paused);draw();requestAnimationFrame(loop)}
window.addEventListener("keydown",e=>{if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight"," ","w","a","s","d","e","E"].includes(e.key))e.preventDefault();if(e.key==="Escape"){if(state.active)closeProblem();else if(state.paused)resume();else pause()}if((e.key==="e"||e.key==="E")&&!state.active)interact();keys.add(e.key)});
window.addEventListener("keyup",e=>keys.delete(e.key));
document.querySelectorAll(".touch-controls [data-key]").forEach(b=>{const k=b.dataset.key;b.addEventListener("pointerdown",()=>keys.add(k));["pointerup","pointercancel","pointerleave"].forEach(ev=>b.addEventListener(ev,()=>keys.delete(k)))});
$("solveBtn").onclick=solve;$("hintBtn").onclick=hint;$("inventoryBtn").onclick=inventory;$("pauseBtn").onclick=pause;$("resumeBtn").onclick=resume;$("finishBtn").onclick=()=>{$("finishModal").classList.add("hidden")};document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).classList.add("hidden"));
$("answer").addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();solve()}});
window.addEventListener("beforeunload",save);restore().then(()=>requestAnimationFrame(loop));
})();