window.MATHVERSE_DATA={zone:{id:"city-of-variables",name:"Ciudad de las Variables",theme:"Álgebra"},problems:[
{id:"battery-alpha",title:"Batería Alpha",story:"La puerta consume 21 unidades. Cada batería aporta 3x + 6. Encuentra el valor que permite estabilizar la red.",equation:"3x + 6 = 21",answer:5,topic:"algebra",hint1:"La energía total debe llegar a 21.",hint2:"Resta 6 a ambos lados antes de dividir.",hint3:"Después de restar 6, divide entre 3.",effect:{type:"energy",value:25,message:"La batería se carga. La red recibe 25 unidades de energía."}},
{id:"lift-beta",title:"Ascensor Beta",story:"El ascensor necesita 30 unidades. Dos celdas iguales aportan 5x + 5 cada una. Ajusta la variable.",equation:"2(5x + 5) = 30",answer:2,topic:"algebra",hint1:"Hay dos celdas idénticas.",hint2:"Primero divide la energía total entre 2.",hint3:"Resuelve 5x + 5 = 15.",effect:{type:"elevator",message:"El ascensor cobra vida y abre una ruta superior."}},
{id:"generator-gamma",title:"Generador Gamma",story:"El generador tiene una salida de 4x + 8. Necesita 28 para activar el distrito.",equation:"4x + 8 = 28",answer:5,topic:"algebra",hint1:"La salida debe alcanzar 28.",hint2:"El 8 es energía fija, no depende de x.",hint3:"Calcula 28 − 8 y luego divide entre 4.",effect:{type:"generator",value:30,message:"El generador despierta. Las farolas de la ciudad se encienden."}},
{id:"door-delta",title:"Puerta Delta",story:"La puerta está bloqueada. Su panel acepta 6x − 4 y necesita 20 unidades.",equation:"6x − 4 = 20",answer:4,topic:"algebra",hint1:"La puerta necesita exactamente 20.",hint2:"Compensa primero el −4.",hint3:"Después de sumar 4, divide entre 6.",effect:{type:"door",message:"Los cierres magnéticos se retraen. El distrito central queda abierto."}},
{id:"bridge-epsilon",title:"Puente Epsilon",story:"Una plataforma requiere una carga de 42. Tres módulos aportan 4x + 2 cada uno.",equation:"3(4x + 2) = 42",answer:3,topic:"algebra",hint1:"Reparte la carga entre los tres módulos.",hint2:"Cada módulo debe aportar 14.",hint3:"Resuelve 4x + 2 = 14.",effect:{type:"bridge",message:"La plataforma se extiende sobre el vacío. Has conectado la ciudad."}}
],tools:[
{id:"variable-scanner",name:"Analizador de Variables",icon:"🔎",desc:"Muestra qué cantidad depende de la variable."},
{id:"vector-viewer",name:"Visor Vectorial",icon:"🧭",desc:"Herramienta preparada para el Circuito Vectorial."},
{id:"builder",name:"Constructor",icon:"🏗️",desc:"Herramienta preparada para MegaConstrucción."},
{id:"finance",name:"Calculadora Financiera",icon:"💳",desc:"Herramienta preparada para Ciudad Económica."}
],levels:[{level:1,name:"Explorador",xp:0},{level:10,name:"Calculador",xp:450},{level:25,name:"Ingeniero",xp:1500},{level:50,name:"Arquitecto Matemático",xp:4000},{level:75,name:"Maestro de los Números",xp:8500},{level:100,name:"Leyenda de Mathverse",xp:15000}]};